stages:
  - test
  - report

variables:
  PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

cache:
  paths:
    - .cache/pip

test:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.58.0-jammy

  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest --alluredir=allure-results

  artifacts:
    when: always
    paths:
      - allure-results
    expire_in: 7 days

report:
  stage: report
  image: eclipse-temurin:17-jdk-jammy   # ✅ FIXED

  dependencies:
    - test

  before_script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
    - unzip allure-2.27.0.zip
    - mv allure-2.27.0 /opt/allure
    - ln -s /opt/allure/bin/allure /usr/bin/allure

  script:
    - allure generate allure-results -o allure-report --clean

  artifacts:
    paths:
      - allure-report
    expire_in: 7 days