[pytest]
addopts = --alluredir=reports --clean-alluredir
testpaths = tests
python_files = test_*.py
markers =
    smoke: critical tests
    regression: full regression suite
    sanity: quick validation tests
    auth: authentication tests
    cart: cart related tests
    checkout: checkout flow tests
    api: api tests
    slow: long running tests